use_directory_urls: false
site_author: Zachary Loeber
copyright: ModuleBuild is licensed under this <a href='https://github.com/zloeber/ModuleBuild/blob/master/License.md'> license
theme: readthedocs
site_name: ModuleBuild Docs
pages:
- Acknowledgements: Acknowledgements.md
- ChangeLog: ChangeLog.md
- Contributing: Contributing.md
- index: index.md
- ToDo: ToDo.md
- Functions:
  - Add-PublicFunction: Functions/Add-PublicFunction.md
  - Get-BuildEnvironment: Functions/Get-BuildEnvironment.md
  - Import-ModulePrivateFunction: Functions/Import-ModulePrivateFunction.md
  - Import-ModulePublicFunction: Functions/Import-ModulePublicFunction.md
  - Initialize-ModuleBuild: Functions/Initialize-ModuleBuild.md
  - Set-BuildEnvironment: Functions/Set-BuildEnvironment.md
- Introduction: Introduction/Introduction.md
- Usage:
  - 1 - Initialization: Usage/1 - Initialization.md
  - 2 - Make Your Module: Usage/2 - Make Your Module.md
  - 3 - Build A Release: Usage/3 - Build A Release.md
  - 4 - Test A Release: Usage/4 - Test A Release.md
  - 5 - Publish A Release: Usage/5 - Publish A Release.md
  - 6 - Your Next Release: Usage/6 - Your Next Release.md
  - 7 - Project Documentation: Usage/7 - Project Documentation.md
  - 8 - Special Files: Usage/8 - Special Files.md
  - 9 - ModuleBuild Configuration: Usage/9 - ModuleBuild Configuration.md
  - 10 - Converting To ModuleBuild: Usage/10 - Converting To ModuleBuild.md
  - 11 - Module Plugins: Usage/11 - Module Plugins.md
repo_url: https://github.com/zloeber/ModuleBuild

